// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef calculator_v2_h
#define calculator_v2_h
#include <FL/Fl.H>
#include "sqlite3.h"

// This application is the first program I've written using fltk and fluid.
// So far I dig fltk 1.4 quite a bit. 

// The goal of the application is allow the user to get a yearly average rate
// of return that takes multiple currency or fixed income positions into account.

// The program currently allows the user to input two currency positions, 
// a fixed income position, and a 3rd currency position.

// currency 1 and 2 can be either positive or negative, currency 3 can 
// only be the result of one of the short currencies. 

// sqlite objects
void load_CB(Fl_Widget*w, void* userdata);
void save_CB(Fl_Widget*w, void* userdata);
void clear_CB(Fl_Widget*w, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *response_window;
#include <FL/Fl_Flex.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *c1_output;
extern Fl_Text_Display *c2_output;
extern Fl_Text_Display *c3_output;
extern Fl_Text_Display *tbill_output;
extern Fl_Text_Display *blended_output;
void Calculate_CB(Fl_Widget*w, void* userdata);
void input_CB(Fl_Widget*w, void* userdata);
void WinQuit_CB(Fl_Widget*, void*);
extern Fl_Double_Window *window;
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
extern Fl_Flex *left_flex;
#include <FL/Fl_Input.H>
extern Fl_Input *input_currency1size;
extern Fl_Input *input_currency1rate;
extern Fl_Input *input_currency3size;
extern Fl_Input *input_currency3rate;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *submit_button;
#include <FL/Fl_Button.H>
extern Fl_Button *clear_button;
extern Fl_Button *save_button;
extern Fl_Button *load_button;
extern Fl_Flex *right_flex;
extern Fl_Input *input_currency2size;
extern Fl_Input *input_currency2rate;
extern Fl_Input *input_tbillsize;
extern Fl_Input *input_tbillrate;
extern Fl_Input *input_newfxrate;
#endif
